"""library groups, duration, source

Revision ID: 4cb013d0d049
Revises: 9e74052b7825
Create Date: 2026-09-12 19:19:43.737344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb013d0d049'
down_revision: Union[str, None] = '9e74052b7825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_groups',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'group_id')
    )
    op.add_column('media_metadata', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('media_metadata', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_metadata', 'source')
    op.drop_column('media_metadata', 'duration_seconds')
    op.drop_table('item_groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
