"""job source, target group, job_targets

Revision ID: 675d005ad046
Revises: 4cb013d0d049
Create Date: 2026-09-13 15:20:37.737879
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675d005ad046'
down_revision: Union[str, None] = '4cb013d0d049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.BigInteger(), nullable=True),
    sa.Column('range_end', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default so existing rows get a value; NOT NULL is then safe.
    op.add_column('jobs', sa.Column('source', sa.String(length=20), nullable=False,
                                    server_default='kinescope'))
    op.add_column('jobs', sa.Column('target_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_jobs_target_group', 'jobs', 'groups',
                          ['target_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_target_group', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'target_group_id')
    op.drop_column('jobs', 'source')
    op.drop_table('job_targets')
    # ### end Alembic commands ###
