"""add agent_url and next_chunk_start

Revision ID: 9e74052b7825
Revises: 4f9b48b05fc8
Create Date: 2026-09-11 19:55:07.468648
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e74052b7825'
down_revision: Union[str, None] = '4f9b48b05fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_chunk_start', sa.BigInteger(), nullable=True))
    op.add_column('workers', sa.Column('agent_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'agent_url')
    op.drop_column('jobs', 'next_chunk_start')
    # ### end Alembic commands ###
